sudo: required
dist: trusty

language: php

services:
  - docker

php:
  - 7.4
  - 8.0
  - 8.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - travis_retry docker run -d --rm --name pdns -p 53:53/udp -p 53:53/tcp -p 80:80 -e "WEBPASSWD=password" raspberrypython/powerdns-sqlite3:latest

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/coveralls
