name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3.0.0
        with:
          version: 9 # PHPUnit version
          php_version: ${{ matrix.php_version }}
          php_extensions: xdebug json
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
          DNS_SERVER_PORT: 1053 # Port 53 is blocked by GitHub
          SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=./tests/baseline-ignore"
    services:
      powerdns:
        image: raspberrypython/powerdns-sqlite3:latest
        env:
          WEBPASSWD: password
        ports:
          - 80:80
          - 1053:53/tcp
          - 1053:53/udp
