name: CI

on: [push, pull_request]

env:
  CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [7.4, 8.0, 8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php_version }}
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3.0.0
        with:
          version: 9 # PHPUnit version
          php_version: ${{ matrix.php_version }}
          php_extensions: xdebug
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text --coverage-clover clover.xml
        env:
          XDEBUG_MODE: coverage
          DNS_SERVER_PORT: 1053 # Port 53 is blocked by GitHub
          SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=./tests/baseline-ignore"
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l PHP -r clover.xml --partial
        if: github.event_name == 'push'
  codacy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) final
